---
id: Compress_Fast
name: Compress_Fast
full: Fast compression library
description: >
  Provides compression suitable for packing strings on-the-fly in PHP code (as
  opposed to more resource-intensive compression algorithms such as DEFLATE).
list: dev
type: library
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: true
    role: lead
version:
  release: 1.1.2
  api: 1.1.0
state:
  release: stable
  api: stable
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Exception: ^2
  optional:
    pear:
      pear.horde.org/Horde_Test: ^2.1
      pear.horde.org/horde_lz4:
        version: '*'
        providesextension: horde_lz4
      pecl.php.net/lzf:
        version: ^1.5.2
        providesextension: lzf
    ext:
      zlib: '*'
