---
id: Compress_Fast
name: Compress_Fast
full: Fast compression library
description: >
  Provides compression suitable for packing strings on-the-fly in PHP code (as
  opposed to more resource-intensive compression algorithms such as DEFLATE).
list: dev
type: library
